name: Build Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  should-i-run:
    name: Build pipeline
    runs-on: ubuntu-latest
    outputs: ${{ steps.set_should_i_run.set_should_i_run }}
    steps:
      - name: Set should I run
        id: set_should_i_run
        run: echo "::set-output name=should_i_run::0"

  build:
    name: Build pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: turn off
        run: export GIT_PR_SHA="${{ github.sha }}"

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - should_i_run
      - build
    runs-on: ubuntu-latest
    steps:
      if ${{ needs.should_i_run.should_i_run == 1 }}
      - name: Slack Workflow Notifications
        if: ${{ github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
